### ISSUE TITLE
Safari support for version 1.3.0

### ISSUE THREAD

**Issue by guillaume-moreau** [paddls/ts-serializer#22]
Hello !

With the version 1.3.0 and the removal of lodash the library is no longer supporting old Safari browsers.
This is because the lib now uses `structuredClone` instead of the lodash function `cloneDeep`.

`structuredClone` is quite new and got a support of Safari starting v15.4: see : [MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)

Is this a wanted behaviour, or do the lib should be compatible with older browsers ? (on our side we support Safari starting v12).

Thank you =)

**Comment by oscar-guerin** [comment]
A good workaround would be to create a polyfill for `structuredClone` in your app. The following piece of code should work correctly for our library use case : `JSON.parse(JSON.stringify(val))`.

Again, sorry for the inconvenience. Closing the issue 🙂
